### ISSUE TITLE
miniserver connect to existing Fi-Fi

### ISSUE THREAD

**Issue by rithythul** [koompi/kcs-docs#2]
When hooked up to existing Fi-Fi, the miniserver should have auto function to be shut down of it-own wifi or merge together and act itself as the server only. 

Avoid conflicting with existing Wifi at the campus.

**Comment by IsaacJReay** [comment]
That function is now available for use and can be demoed from https://admin.koompi.app online and on all offline. For online username and password for login, please request through my telegram DM
